import type { NextRequest } from "next/server"

export async function POST(req: NextRequest) {
  try {
    // Try forwarding to Python backend if configured
    if (process.env.BACKEND_URL) {
      const body = await req.json().catch(() => ({}))
      const res = await fetch(`${process.env.BACKEND_URL}/letters/approval`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(body),
      })
      if (res.ok) {
        const data = await res.json().catch(async () => ({ text: await res.text() }))
        return new Response(JSON.stringify(data), { status: 200 })
      }
    }
  } catch {
    // fall through to demo
  }

  // Demo fallback letter
  const ref = Math.floor(Math.random() * 1_000_000)
  const demo = {
    text: `Government of India
Approval Letter

Ref: GOI/${ref}/${new Date().getFullYear()}

This is a demo approval confirmation for your application.
This letter is autogenerated for testing purposes only.

Authorized Signatory`,
  }
  return new Response(JSON.stringify(demo), { status: 200 })
}
